name = "app"
version = "1.0.0"
target = "javascript"

[dependencies]
common = { path = "../common" }
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.2.5 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.3.2 and < 2.0.0"
